name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true
        continue-on-error: false

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run all tests
        run: |
          npx playwright test tests/pomTests/
          npx playwright test tests/ddtTests/
          npx cucumber-js tests/bddTests/features/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30